/**
 * 教程自有的浏览器 TinyGPU 仿真器。
 * 与 tools/tinygpu_sim.py 对齐：16 个 8-bit 寄存器、256-byte 全局内存、
 * 64-byte shared memory，及 FETCH/DECODE/REQUEST/WAIT/EXECUTE/UPDATE 流水级。
 */
import { Instruction, Opcode, OPCODE_NAMES, PipelineStage, SimulationState, ThreadState } from './types';
interface Decoded { opcode:number; rd:number; rs:number; rt:number; imm:number; nzpMask:number; result?:number; addr?:number; data?:number; read?:number; }

export class TinyGPUSim {
  private readonly program:number[]; private memory:number[]; private shared:number[] = Array(64).fill(0); private threads:ThreadState[]=[]; private decoded=new Map<number,Decoded>(); private block=0; private cycle=0;
  constructor(instructions:Instruction[], memory:number[], private readonly blocks=1, private readonly lanes=4, private readonly registers:number[]=[]){ this.program=instructions.map((item)=>Number.parseInt(item.hex,16)&0xffff); this.memory=Array(256).fill(0); memory.slice(0,256).forEach((value,index)=>this.memory[index]=value&0xff); this.initBlock(0); }
  private initBlock(blockId:number){ this.block=blockId; this.shared=Array(64).fill(0); this.decoded.clear(); this.threads=Array.from({length:this.lanes},(_,threadId)=>{ const regs=Array(16).fill(0); this.registers.forEach((value,index)=>{if(index<13) regs[index]=value&0xff;}); regs[13]=blockId&0xff; regs[14]=this.lanes&0xff; regs[15]=threadId&0xff; return {threadId,blockId,pc:0,registers:regs,nzp:2,stage:'FETCH' as PipelineStage,done:false,currentInstruction:'',divergent:false}; }); }
  private key(thread:ThreadState){ return thread.threadId+thread.blockId*1000; }
  isDone(){ return this.block>=this.blocks; }
  getState():SimulationState { return {cycle:this.cycle,currentBlock:this.block,totalBlocks:this.blocks,memory:[...this.memory],sharedMemory:[...this.shared],threads:this.threads.map((thread)=>({...thread,registers:[...thread.registers]}))}; }
  runToEnd(maxCycles=10000){ const history=[this.getState()]; while(!this.isDone()&&this.cycle<maxCycles) history.push(this.step()); return history; }
  step():SimulationState { if(this.isDone()) return this.getState(); if(this.threads.every((thread)=>thread.done)){ this.block++; if(!this.isDone()) this.initBlock(this.block); this.cycle++; return this.getState(); } const barrier=this.threads.filter((thread)=>!thread.done&&thread.stage==='BARRIER'); if(barrier.length){ const active=this.threads.filter((thread)=>!thread.done); if(barrier.length===active.length) barrier.forEach((thread)=>{thread.stage='FETCH';thread.pc++;}); else this.threads.forEach((thread)=>{if(!thread.done&&thread.stage!=='BARRIER')this.execThread(thread);}); this.cycle++; return this.getState(); } const active=this.threads.filter((thread)=>!thread.done); const counts=new Map<number,number>(); active.forEach((thread)=>counts.set(thread.pc,(counts.get(thread.pc)??0)+1)); const majority=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??0; this.threads.forEach((thread)=>{thread.divergent=!thread.done&&thread.pc!==majority;if(!thread.done)this.execThread(thread);}); this.cycle++; return this.getState(); }
  private execThread(thread:ThreadState){ if(thread.stage==='FETCH')this.fetch(thread); else if(thread.stage==='DECODE')this.decode(thread); else if(thread.stage==='REQUEST')this.request(thread); else if(thread.stage==='WAIT')this.wait(thread); else if(thread.stage==='EXECUTE')this.execute(thread); else if(thread.stage==='UPDATE')this.update(thread); }
  private fetch(thread:ThreadState){ if(thread.pc>=this.program.length){thread.done=true;thread.stage='DONE';return;} const opcode=(this.program[thread.pc]>>12)&15; thread.currentInstruction=OPCODE_NAMES[opcode]??'UNK';thread.stage='DECODE'; }
  private decode(thread:ThreadState){ const word=this.program[thread.pc];this.decoded.set(this.key(thread),{opcode:(word>>12)&15,rd:(word>>8)&15,rs:(word>>4)&15,rt:word&15,imm:word&255,nzpMask:(word>>9)&7});thread.stage='REQUEST'; }
  private request(thread:ThreadState){ const d=this.decoded.get(this.key(thread))!; if(d.opcode===Opcode.LDR||d.opcode===Opcode.STR)d.addr=thread.registers[d.rs]&255; if(d.opcode===Opcode.STR)d.data=thread.registers[d.rt]&255; if(d.opcode===Opcode.SLDR||d.opcode===Opcode.SSTR)d.addr=thread.registers[d.rs]&63; if(d.opcode===Opcode.SSTR)d.data=thread.registers[d.rt]&255;thread.stage='WAIT'; }
  private wait(thread:ThreadState){ const d=this.decoded.get(this.key(thread))!;if(d.opcode===Opcode.LDR)d.read=this.memory[d.addr??0];else if(d.opcode===Opcode.STR)this.memory[d.addr??0]=d.data??0;else if(d.opcode===Opcode.SLDR)d.read=this.shared[d.addr??0];else if(d.opcode===Opcode.SSTR)this.shared[d.addr??0]=d.data??0;thread.stage='EXECUTE'; }
  private execute(thread:ThreadState){ const d=this.decoded.get(this.key(thread))!,r=thread.registers;const binary=(fn:(a:number,b:number)=>number)=>d.result=fn(r[d.rs],r[d.rt])&255;switch(d.opcode){case Opcode.ADD:binary((a,b)=>a+b);break;case Opcode.SUB:binary((a,b)=>a-b);break;case Opcode.MUL:binary((a,b)=>a*b);break;case Opcode.DIV:binary((a,b)=>b?Math.floor(a/b):0);break;case Opcode.CMP:{const x=r[d.rs]-r[d.rt];d.result=(x<0?4:0)|(x===0?2:0)|(x>0?1:0);break;}case Opcode.CONST:d.result=d.imm;break;case Opcode.LDR:case Opcode.SLDR:d.result=d.read??0;break;}thread.stage='UPDATE'; }
  private update(thread:ThreadState){ const key=this.key(thread),d=this.decoded.get(key)!;if([Opcode.ADD,Opcode.SUB,Opcode.MUL,Opcode.DIV,Opcode.CONST,Opcode.LDR,Opcode.SLDR].includes(d.opcode)){thread.registers[d.rd]=(d.result??0)&255;thread.pc++;}else if(d.opcode===Opcode.CMP){thread.nzp=(d.result??0)&7;thread.pc++;}else if([Opcode.NOP,Opcode.STR,Opcode.SSTR].includes(d.opcode))thread.pc++;else if(d.opcode===Opcode.BAR){thread.stage='BARRIER';this.decoded.delete(key);return;}else if(d.opcode===Opcode.BRNZP)thread.pc=thread.nzp&d.nzpMask?d.imm:thread.pc+1;else if(d.opcode===Opcode.RET){thread.done=true;thread.stage='DONE';this.decoded.delete(key);return;}this.decoded.delete(key);thread.stage='FETCH'; }
}
